desc "Upload To Internal Track"
lane :beta do
    upload_to_play_store(
        aab: File.expand_path('../..', __dir__) + '/build/app/outputs/bundle/release/app-release.aab',
        json_key: File.expand_path('../..', __dir__) + '/play_store_credentials.json',
        status: 'draft',
        track: 'internal'
    )
end

desc "Upload To Production Track"
lane :production do
    upload_to_play_store(
        aab: File.expand_path('../..', __dir__) + '/build/app/outputs/bundle/release/app-release.aab',
        json_key: File.expand_path('../..', __dir__) + '/play_store_credentials.json',
        track: 'production'
    )
end
